---
- name: Gather IOS-XE facts
  hosts: proxmox_routers
  connection: network_cli 
  tasks:
    - name: Gather IOS Facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: what is the IOS OS ver?
      debug:
        var: ansible_net_version 
        
    - name: What is the hostname?
      debug:
        var: ansible_net_hostname 
