---
- hosts: linux_servers
  become: yes
  
  tasks:
    - name: Install vsftpd 
      apt: name = vsftpd state = "latest"
      when: ansible_os_family = ="debian" 
     
   - name: Install vsftpd
     yum: name = vsftpd state ="latest"
     when: ansible_os_family == "RedHat"
     
   - name: install stuff
     apt:  name={{ item }} update_cache=yes state=latest
     with_items:
       - vim
       - nano 
       - apache2
