---
- name: Get stats and write to desktop
  hosts: linux_hosts
  tasks:
    - name: get system status and info
      shell: uname -a  > /home/ansible/Desktop/output.txt
    - name: print my username 
      shell: whoami >> /home/ansible/Desktop/output.txt  
